ALTER TABLE "User" ADD COLUMN "permanentBan" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "UserBan" ADD COLUMN "permanent" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "UserBan" ALTER COLUMN "endAt" DROP NOT NULL;
